version: "3.4"

services:
    mysql:
        image: leafney/alpine-mariadb:latest
        container_name: mysql
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PWD=123
            - MYSQL_USER=dev
            - MYSQL_USER_PWD=dev
            - MYSQL_USER_DB=userdb
        volumes:
            - ./databases/mysql:/var/lib/mysql
        network_mode: host