version: "3"

services:
    mysql:
        image: yobasystems/alpine-mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        expose:
            - "3306"
        volumes:
            - ./databases/mysql:/var/lib/mysql
        restart: always

